In [1]:
# All Libraries required for this lab are listed below. The libraries pre-installed on Skills Network Labs are commented.
# !mamba install -qy pandas==1.3.4 numpy==1.21.4 seaborn==0.9.0 matplotlib==3.5.0 scikit-learn==0.20.1
# Note: If your environment doesn't support "!mamba install", use "!pip install"

In [2]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [3]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

In [4]:
from pyodide.http import pyfetch

async def download(url, filename):
    response = await pyfetch(url)
    if response.status == 200:
        with open(filename, "wb") as f:
            f.write(await response.bytes())

In [5]:
path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [6]:
await download(path, "Weather_Data.csv")
filename ="Weather_Data.csv"

In [7]:
df = pd.read_csv("Weather_Data.csv")

In [8]:
#filepath = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv"
#df = pd.read_csv(filepath)

In [9]:
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [10]:
df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

In [11]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

In [12]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [13]:
df_sydney_processed = df_sydney_processed.astype(float)

In [14]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']

In [15]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, Y, test_size=0.2, random_state=10)

In [16]:
from sklearn.linear_model import LinearRegression

LinearReg = LinearRegression()  # Crea el modelo

LinearReg.fit(X_train, y_train)  # Entrena el modelo

LinearRegression()

In [17]:
predictions = LinearReg.predict(X_test)

In [18]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# Calcular MSE
mse = mean_squared_error(y_test, predictions)

# Calcular RMSE
rmse = mean_squared_error(y_test, predictions, squared=False) # squared=False para RMSE

# Calcular MAE
mae = mean_absolute_error(y_test, predictions)

# Calcular R-cuadrado
r2 = r2_score(y_test, predictions)

print(f"MSE: {mse}")
print(f"RMSE: {rmse}")
print(f"MAE: {mae}")
print(f"R-cuadrado: {r2}")

MSE: 0.1157209828234031
RMSE: 0.3401778693910042
MAE: 0.256318933909176
R-cuadrado: 0.4271301272061002


In [19]:
import pandas as pd
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

# ... (cálculo de mse, rmse, mae y r2 como en la respuesta anterior) ...

# Crear un diccionario con las métricas
metrics = {
    'MAE': [mae],
    'MSE': [mse],
    'R²': [r2]
}

# Crear el DataFrame
metrics_df = pd.DataFrame(metrics)

# Mostrar el DataFrame
print(metrics_df)

        MAE       MSE       R²
0  0.256319  0.115721  0.42713


In [20]:
from sklearn.neighbors import KNeighborsClassifier  # Para clasificación (RainTomorrow es categórica)

KNN = KNeighborsClassifier(n_neighbors=4)  # Crea el modelo KNN

KNN.fit(X_train, y_train)  # Entrena el modelo

KNeighborsClassifier(n_neighbors=4)

In [21]:
predictions = KNN.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Calcular la exactitud (accuracy)
accuracy = accuracy_score(y_test, predictions)

# Calcular la precisión (precision)
precision = precision_score(y_test, predictions)

# Calcular el recall
recall = recall_score(y_test, predictions)

# Calcular el F1-score
f1 = f1_score(y_test, predictions)

# Calcular la matriz de confusión
cm = confusion_matrix(y_test, predictions)

print(f"Exactitud (Accuracy): {accuracy}")
print(f"Precisión (Precision): {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")
print("Matriz de Confusión:\n", cm)

Exactitud (Accuracy): 0.8183206106870229
Precisión (Precision): 0.7927927927927928
Recall: 0.4782608695652174
F1-score: 0.5966101694915255
Matriz de Confusión:
 [[448  23]
 [ 96  88]]


In [23]:
from sklearn.tree import DecisionTreeClassifier  # Para clasificación (RainTomorrow es categórica)

Tree = DecisionTreeClassifier()  # Crea el modelo de Árbol de Decisión

Tree.fit(X_train, y_train)  # Entrena el modelo

DecisionTreeClassifier()

In [24]:
predictions = Tree.predict(X_test)

In [25]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

# Calcular la exactitud (accuracy)
accuracy = accuracy_score(y_test, predictions)

# Calcular la precisión (precision)
precision = precision_score(y_test, predictions)

# Calcular el recall
recall = recall_score(y_test, predictions)

# Calcular el F1-score
f1 = f1_score(y_test, predictions)

# Calcular la matriz de confusión
cm = confusion_matrix(y_test, predictions)

print(f"Exactitud (Accuracy): {accuracy}")
print(f"Precisión (Precision): {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")
print("Matriz de Confusión:\n", cm)

Exactitud (Accuracy): 0.7480916030534351
Precisión (Precision): 0.5513513513513514
Recall: 0.5543478260869565
F1-score: 0.5528455284552846
Matriz de Confusión:
 [[388  83]
 [ 82 102]]


In [26]:
from sklearn.model_selection import train_test_split

X_train1, X_test1, y_train1, y_test1 = train_test_split(features, Y, test_size=0.2, random_state=1)

In [27]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(solver='liblinear')  # Crea el modelo de Regresión Logística

LR.fit(X_train, y_train)  # Entrena el modelo

LogisticRegression(solver='liblinear')

In [28]:
predictions = LR.predict(X_test)
predict_proba = LR.predict_proba(X_test)

In [29]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score

# Calcular la exactitud (accuracy)
accuracy = accuracy_score(y_test, predictions)

# Calcular la precisión (precision)
precision = precision_score(y_test, predictions)

# Calcular el recall
recall = recall_score(y_test, predictions)

# Calcular el F1-score
f1 = f1_score(y_test, predictions)

# Calcular la matriz de confusión
cm = confusion_matrix(y_test, predictions)

# Calcular el área bajo la curva ROC (AUC)
auc = roc_auc_score(y_test, predict_proba[:, 1]) # predict_proba[:, 1] selecciona la probabilidad de la clase positiva (lluvia)

print(f"Exactitud (Accuracy): {accuracy}")
print(f"Precisión (Precision): {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")
print("Matriz de Confusión:\n", cm)
print(f"AUC: {auc}")

Exactitud (Accuracy): 0.8381679389312977
Precisión (Precision): 0.76
Recall: 0.6195652173913043
F1-score: 0.6826347305389222
Matriz de Confusión:
 [[435  36]
 [ 70 114]]
AUC: 0.8964160435705715


In [30]:
from sklearn.svm import SVC  # Para clasificación (RainTomorrow es categórica)

SVM = SVC()  # Crea el modelo SVM

SVM.fit(X_train, y_train)  # Entrena el modelo

SVC()

In [31]:
predictions = SVM.predict(X_test)

In [32]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, roc_auc_score

# Calcular la exactitud (accuracy)
accuracy = accuracy_score(y_test, predictions)

# Calcular la precisión (precision)
precision = precision_score(y_test, predictions)

# Calcular el recall
recall = recall_score(y_test, predictions)

# Calcular el F1-score
f1 = f1_score(y_test, predictions)

# Calcular la matriz de confusión
cm = confusion_matrix(y_test, predictions)

# Para calcular el AUC, necesitas predict_proba.  SVM no da predict_proba por defecto,
# a menos que se configure con probability=True durante la creación del modelo.
# Si no lo hiciste, no podrás calcular el AUC directamente.

# Ejemplo (si hubieras configurado probability=True):
# try:
#     auc = roc_auc_score(y_test, SVM.decision_function(X_test)) # Usamos decision_function en SVM
#     print(f"AUC: {auc}")
# except AttributeError:
#     print("No se puede calcular AUC.  Entrena el modelo SVM con probability=True.")


print(f"Exactitud (Accuracy): {accuracy}")
print(f"Precisión (Precision): {precision}")
print(f"Recall: {recall}")
print(f"F1-score: {f1}")
print("Matriz de Confusión:\n", cm)

Exactitud (Accuracy): 0.7190839694656489
Precisión (Precision): 0.0
Recall: 0.0
F1-score: 0.0
Matriz de Confusión:
 [[471   0]
 [184   0]]


In [33]:
import pandas as pd
from sklearn.metrics import accuracy_score, jaccard_score, f1_score, log_loss, classification_report

# ... (Código para entrenar los modelos KNN, Tree, LR y SVM usando X_train, y_train) ...

# Predicciones para cada modelo
predictions_knn = KNN.predict(X_test)
predictions_tree = Tree.predict(X_test)
predictions_lr = LR.predict(X_test)
predictions_svm = SVM.predict(X_test)

# Probabilidades para Regresión Logística (necesario para Log Loss)
predict_proba_lr = LR.predict_proba(X_test)

# Calcula las métricas para cada modelo
accuracy_knn = accuracy_score(y_test, predictions_knn)
jaccard_knn = jaccard_score(y_test, predictions_knn)
f1_knn = f1_score(y_test, predictions_knn)

accuracy_tree = accuracy_score(y_test, predictions_tree)
jaccard_tree = jaccard_score(y_test, predictions_tree)
f1_tree = f1_score(y_test, predictions_tree)

accuracy_lr = accuracy_score(y_test, predictions_lr)
jaccard_lr = jaccard_score(y_test, predictions_lr)
f1_lr = f1_score(y_test, predictions_lr)
log_loss_lr = log_loss(y_test, predict_proba_lr)

accuracy_svm = accuracy_score(y_test, predictions_svm)
jaccard_svm = jaccard_score(y_test, predictions_svm)
f1_svm = f1_score(y_test, predictions_svm)


# Crea un diccionario con las métricas para cada modelo
model_metrics = {
    'KNN': {
        'Accuracy': accuracy_knn,
        'Jaccard Index': jaccard_knn,
        'F1-Score': f1_knn,
        'Log Loss': None  # No aplicable
    },
    'Decision Tree': {
        'Accuracy': accuracy_tree,
        'Jaccard Index': jaccard_tree,
        'F1-Score': f1_tree,
        'Log Loss': None  # No aplicable
    },
    'Logistic Regression': {
        'Accuracy': accuracy_lr,
        'Jaccard Index': jaccard_lr,
        'F1-Score': f1_lr,
        'Log Loss': log_loss_lr
    },
    'SVM': {
        'Accuracy': accuracy_svm,
        'Jaccard Index': jaccard_svm,
        'F1-Score': f1_svm,
        'Log Loss': None  # No aplicable
    }
}

# Crear el DataFrame
metrics_df = pd.DataFrame.from_dict(model_metrics, orient='index')

# Mostrar el DataFrame
print(metrics_df)

# Informes de clasificación (opcional, pero recomendado)
print("\nInformes de Clasificación:")
print("KNN:\n", classification_report(y_test, predictions_knn))
print("\nÁrbol de Decisión:\n", classification_report(y_test, predictions_tree))
print("\nRegresión Logística:\n", classification_report(y_test, predictions_lr))
print("\nSVM:\n", classification_report(y_test, predictions_svm))

                     Accuracy  Jaccard Index  F1-Score  Log Loss
KNN                  0.818321       0.425121  0.596610       NaN
Decision Tree        0.748092       0.382022  0.552846       NaN
Logistic Regression  0.838168       0.518182  0.682635  0.357721
SVM                  0.719084       0.000000  0.000000       NaN

Informes de Clasificación:
KNN:
               precision    recall  f1-score   support

         0.0       0.82      0.95      0.88       471
         1.0       0.79      0.48      0.60       184

    accuracy                           0.82       655
   macro avg       0.81      0.71      0.74       655
weighted avg       0.81      0.82      0.80       655


Árbol de Decisión:
               precision    recall  f1-score   support

         0.0       0.83      0.82      0.82       471
         1.0       0.55      0.55      0.55       184

    accuracy                           0.75       655
   macro avg       0.69      0.69      0.69       655
weighted avg       0.

In [34]:
# Predicciones de cada modelo
predicciones_knn = knn.predict(X_test)
predicciones_arbol = arbol.predict(X_test)
predicciones_lr = lr.predict(X_test)
predicciones_svm = svm.predict(X_test)

# Valores reales de lluvia en el conjunto de prueba
real_lluvia = y_test

<class 'NameError'>: name 'knn' is not defined

In [35]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split  # Si aún no lo has hecho

# ... (Carga tus datos y divide en X_train, y_train, X_test, y_test) ...
# Ejemplo de división:
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 1. Crear el modelo KNN
knn = KNeighborsClassifier(n_neighbors=5)  # Ajusta n_neighbors si es necesario

# 2. Entrenar el modelo
knn.fit(X_train, y_train)

# 3. Hacer predicciones
predicciones_knn = knn.predict(X_test)

# Imprimir las predicciones (opcional)
print(predicciones_knn)

# ... (Repite estos pasos para los otros modelos: árbol de decisión, regresión logística, SVM) ...

# Ejemplo para el árbol de decisión:
from sklearn.tree import DecisionTreeClassifier
arbol = DecisionTreeClassifier()
arbol.fit(X_train, y_train)
predicciones_arbol = arbol.predict(X_test)

# ... (Y así sucesivamente para los demás modelos) ...

# Crear la tabla de comparación
tabla_comparacion = pd.DataFrame({
    'Real': y_test,  # Usar y_test para los valores reales
    'KNN': predicciones_knn,
    'Árbol': predicciones_arbol,
    # ... (añade las predicciones de los otros modelos)
})

print(tabla_comparacion)

# Matriz de confusión (ejemplo para KNN)
from sklearn.metrics import confusion_matrix
matriz_confusion_knn = confusion_matrix(y_test, predicciones_knn) # Usar y_test
print(matriz_confusion_knn)

[0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 1. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0.
 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0.
 0. 0. 1. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 1. 1. 0.
 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1.
 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0.

In [36]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix

# Datos de ejemplo (reemplaza con tus datos reales)
real_lluvia = np.array([0, 0, 1, 1, 0, 1, 0, 1, 0, 1])  # Valores reales
predicciones_knn = np.array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0])  # Predicciones KNN
predicciones_arbol = np.array([0, 0, 1, 0, 0, 1, 0, 1, 1, 1])  # Predicciones Árbol

# 1. Crear un DataFrame con los datos
tabla_comparacion = pd.DataFrame({
    'Real': real_lluvia,
    'KNN': predicciones_knn,
    'Árbol': predicciones_arbol
})

# 2. Mostrar la tabla
print("Tabla de comparación:")
print(tabla_comparacion)

# 3. Calcular y mostrar la matriz de confusión para cada modelo
modelos = {'KNN': predicciones_knn, 'Árbol': predicciones_arbol}
for nombre_modelo, predicciones in modelos.items():
    matriz_confusion = confusion_matrix(real_lluvia, predicciones)
    print(f"\nMatriz de confusión para {nombre_modelo}:")
    print(matriz_confusion)

    # 4. (Opcional) Convertir la matriz de confusión a un DataFrame para mejor visualización
    df_matriz = pd.DataFrame(matriz_confusion, 
                             index=['Real 0', 'Real 1'], 
                             columns=['Pred 0', 'Pred 1'])
    print(df_matriz)

Tabla de comparación:
   Real  KNN  Árbol
0     0    0      0
1     0    1      0
2     1    1      1
3     1    0      0
4     0    0      0
5     1    1      1
6     0    1      0
7     1    1      1
8     0    0      1
9     1    0      1

Matriz de confusión para KNN:
[[3 2]
 [2 3]]
        Pred 0  Pred 1
Real 0       3       2
Real 1       2       3

Matriz de confusión para Árbol:
[[4 1]
 [1 4]]
        Pred 0  Pred 1
Real 0       4       1
Real 1       1       4


In [38]:
import pandas as pd

# Load your data
df = pd.read_csv("Weather_Data.csv")  # Replace with your file name

# Convert 'Date' column to datetime objects
df['Date'] = pd.to_datetime(df['Date'])

# Extract month and year
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

# Find unique months and years
unique_months = df.groupby('Year')['Month'].unique()

print(unique_months)

Year
2008       [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2009    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2010    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2011       [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12]
2012        [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
2013       [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2014    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2015    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2016    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
2017                         [1, 2, 3, 4, 5, 6]
Name: Month, dtype: object


In [40]:
import pandas as pd

# ... (your code to load the CSV and convert 'Date' to datetime) ...

unique_months = df.groupby('Year')['Month'].unique()

# More readable output (Corrected):
for year, months in unique_months.items():
    print(f"Year {year}: Months {months.tolist()}")  # Directly use tolist() on the NumPy array

# Creating a new DataFrame (Corrected):
months_data = []
for year, months in unique_months.items():
    for month in months:
        months_data.append({'Year': year, 'Month': month})

months_df = pd.DataFrame(months_data)
print(months_df)

# Now you can easily filter, group, etc. this months_df
print(months_df[months_df['Year'] == 2011])

Year 2008: Months [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2009: Months [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2010: Months [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2011: Months [1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2012: Months [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
Year 2013: Months [1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2014: Months [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2015: Months [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2016: Months [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
Year 2017: Months [1, 2, 3, 4, 5, 6]
     Year  Month
0    2008      2
1    2008      3
2    2008      4
3    2008      5
4    2008      6
..    ...    ...
105  2017      2
106  2017      3
107  2017      4
108  2017      5
109  2017      6

[110 rows x 2 columns]
    Year  Month
35  2011      1
36  2011      2
37  2011      3
38  2011      5
39  2011      6
40  2011      7
41  2011      8
42  2011      9
43  2011     10
44  2011     11
45  2011     12


In [42]:
import pandas as pd

# 1. Carga tu archivo CSV
df = pd.read_csv("Weather_Data.csv")  # Reemplaza "tu_archivo.csv" con el nombre de tu archivo

# 2. Convierte la columna 'Date' a formato datetime
df['Date'] = pd.to_datetime(df['Date'])

# 3. Identifica los días lluviosos
# Asumimos que si 'Rainfall' es mayor que 0, se considera un día lluvioso
dias_lluviosos = df[df['Rainfall'] > 0]

# 4. Cuenta los días lluviosos por año y mes (opcional)
conteo_dias_lluviosos = dias_lluviosos.groupby([dias_lluviosos['Date'].dt.year, dias_lluviosos['Date'].dt.month]).size().reset_index(name='Cantidad_dias_lluviosos')

# 5. Imprime los resultados
print("Días lluviosos:")
print(dias_lluviosos)

print("\nConteo de días lluviosos por año y mes:")
print(conteo_dias_lluviosos)

<class 'ValueError'>: cannot insert Date, already exists